#!/usr/bin/env python

import sys

import hello
import goodbye


def respond(hello, goodbye):
    they_said = raw_input()
    if they_said in goodbye.goodbyes:
        goodbye.say_it()
        sys.exit(0)
    else:
        if they_said in hello.hellos:
            hello.say_it()
        else:
            print 'eh?'
        respond(hello, goodbye)


if __name__ == '__main__':
    h = hello.Hello()
    g = goodbye.Goodbye()
    h.greet()
    respond(h, g)
