#!/usr/bin/env python
import library


def listen(lib):
    sentence = raw_input()
    inp = [sentence]
    what = lib.get_phrase_types(inp)
    ret = lib.get_responses(what)
    print '\n'
    for p in lib.get_phrases(ret):
        print p
    listen(lib)


if __name__ == '__main__':
    lib = library.Library()
    listen(lib)
